title: "dethrtdggthrhergshjrythedfsgrv"
description: "I put random shit here"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  guides:
    output: true
    permalink: /guides/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: docs

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
